allow_anonymous true
connection_messages true
log_type all

# port 1883      # 기본 MQTT
# listener 8883  # MQTTS (TLS 암호화)
# listener 9001  # MQTT over WebSocket

# listener 1883 192.168.0.10  # 내부망 IP로만 1883 포트 수신
listener 1883

# 영속성 설정 추가 (QoS 1 메시지 처리를 위해 필수)
persistence true
persistence_location /mosquitto/data/

# ACL 파일 경로 지정 (익명 사용자 권한 부여를 위해 필수)
acl_file /mosquitto/config/acl