version: 'latest'
services:
  mosquitto:
    image: "eclipse-mosquitto"
    container_name: "mqtt-broker-mosquitto"
    ports:
      - "1883:1883"
#      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/password:/mosquitto/config/password
      - ./config/acl:/mosquitto/config/acl
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: always